name: Besana CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Besana
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Deploy to production'
      uses: burnett01/rsync-deployments@23a557dceb19f9bb960ef40cf75cab5e9b37ec1f
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /var/www/html/codeploy
        remote_host: ${{ secrets.HOSTNAME }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync vendor packages
      uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
      with:
        hosts: '${{ secrets.REMOTE_USER }}@${{ secrets.HOSTNAME }}'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd /var/www/html/codeploy
          sudo cp .env.example .env
          sudo echo DB_CONNECTION =  ${{ secrets.BESANA_CONNECTION }} > .env
          sudo echo DB_HOST=${{ secrets.BESANA_HOST }} > .env
          sudo echo DB_PORT=${{ secrets.BESANA_PORT }} > .env
          sudo echo DB_DATABASE=${{ secrets.BESANA_DATABASE }} > .env
          sudo echo DB_USERNAME=${{ secrets.BESANA_USERNAME }} > .env
          sudo echo DB_PASSWORD=${{ secrets.BESANA_PASSWORD }} > .env
          sudo composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          sudo php artisan key:generate
          sudo chmod -R 777 storage bootstrap/cache
          sudo php artisan config:cache
          sudo chown -R ubuntu:ubuntu vendor
      env:
        DB_CONNECTION: ${{ secrets.BESANA_CONNECTION }}
        DB_DATABASE: ${{ secrets.BESANA_DATABASE }}
